const data = [
  {
    id: "P97989778",
    image:
      "https://www.sephora.com/productimages/sku/s2518959-main-grid.jpg?pb=allure-2022-bestofbeauty-badge",
    name: "Rare Beauty by Selena Gomez",
    price: 20.0,
    category: "Face",
  },
  {
    id: "P503679",
    image: "https://www.sephora.com/productimages/sku/s2620235-main-grid.jpg",
    name: "MAKEUP BY MARIO",
    price: 42.0,
    category: "Face",
  },
  {
    id: "P434104",
    image: "https://www.sephora.com/productimages/sku/s2419786-main-grid.jpg",
    name: "Charlotte Tilbury",
    price: 46.0,
    category: "Face",
  },
  {
    id: "P38855877",
    image: "https://www.sephora.com/productimages/sku/s2362168-main-grid.jpg",
    name: "Rare Beauty by Selena Gomez",
    price: 22.0,
    category: "Face",
  },
  {
    id: "P503714",
    image: "https://www.sephora.com/productimages/sku/s2629418-main-grid.jpg",
    name: "Rare Beauty by Selena Gomez",
    price: 24.0,
    category: "Face",
  },
  {
    id: "P433526",
    image: "https://www.sephora.com/productimages/sku/s2606085-main-grid.jpg",
    name: "Charlotte Tilbury",
    price: 26.0,
    category: "Face",
  },
  {
    id: "P456151",
    image:
      "https://www.sephora.com/productimages/sku/s2333771-main-grid.jpg?pb=clean-planet-positive-badge-2021",
    name: "Kosas",
    price: 28.0,
    category: "Face",
  },
  {
    id: "P377873",
    image: "https://www.sephora.com/productimages/sku/s2172310-main-grid.jpg",
    name: "NARS",
    price: 14.0,
    category: "Face",
  },
  {
    id: "P461147",
    image: "https://www.sephora.com/productimages/sku/s2368439-main-grid.jpg",
    name: "Charlotte Tilbury",
    price: 36.0,
    category: "Face",
  },
  {
    id: "P434002",
    image: "https://www.sephora.com/productimages/sku/s2115954-main-grid.jpg",
    name: "Charlotte Tilbury",
    price: 40.0,
    category: "Face",
  },

  {
    id: "P503713",
    image: "https://www.sephora.com/productimages/sku/s2629418-main-grid.jpg",
    name: "Rare Beauty by Selena Gomez",
    price: 24.0,
    category: "Eye",
  },
  {
    id: "P377873",
    image: "https://www.sephora.com/productimages/sku/s2172310-main-grid.jpg",
    name: "NARS",
    price: 14.0,
    category: "Eye",
  },
  {
    id: "P501445",
    image: "https://www.sephora.com/productimages/sku/s2612216-main-grid.jpg",
    name: "Too Faced",
    price: 54.0,
    category: "Eye",
  },
  {
    id: "P500423",
    image: "https://www.sephora.com/productimages/sku/s2532588-main-grid.jpg",
    name: "The Ordinary",
    price: 14.5,
    category: "Eye",
  },
  {
    id: "P502501",
    image: "https://www.sephora.com/productimages/sku/s2614840-main-grid.jpg",
    name: "tarte",
    price: 54.0,
    category: "Eye",
  },
  {
    id: "P5024439",
    image: "https://www.sephora.com/productimages/sku/s2614873-main-grid.jpg",
    name: "tarte",
    price: 40.0,
    category: "Eye",
  },
  {
    id: "P468341",
    image: "https://www.sephora.com/productimages/sku/s2411486-main-grid.jpg",
    name: "Anastasia Beverly Hills",
    price: 23.0,
    category: "Eye",
  },
  {
    id: "P501354",
    image: "https://www.sephora.com/productimages/sku/s2619096-main-grid.jpg",
    name: "PAT McGRATH LABS",
    price: 82.0,
    category: "Eye",
  },
  {
    id: "P503050",
    image: "https://www.sephora.com/productimages/sku/s2614659-main-grid.jpg",
    name: "Anastasia Beverly Hills",
    price: 39.0,
    category: "Eye",
  },
  {
    id: "P1897503",
    image: "https://www.sephora.com/productimages/sku/s2589927-main-grid.jpg",
    name: "Fenty Beauty by Rihanna",
    price: 28.0,
    category: "Eye",
  },
  {
    id: "P381000",
    image: "https://www.sephora.com/productimages/sku/s1533439-main-grid.jpg",
    name: "Too Faced",
    price: 42.5,
    category: "Eye",
  },

  {
    id: "P453814",
    image: "https://www.sephora.com/productimages/sku/s2449130-main-grid.jpg",
    name: "Dior",
    price: 38.0,
    category: "Lip",
  },
  {
    id: "P5011536",
    image: "https://www.sephora.com/productimages/sku/s2619898-main-grid.jpg",
    name: "Givenchy",
    price: 50.0,
    category: "Lip",
  },
  {
    id: "P479337",
    image: "https://www.sephora.com/productimages/sku/s2514909-main-grid.jpg",
    name: "NARS",
    price: 26.0,
    category: "Lip",
  },
  {
    id: "P443563",
    image: "https://www.sephora.com/productimages/sku/s2210482-main-grid.jpg",
    name: "LANEIGE",
    price: 17.0,
    category: "Lip",
  },
  {
    id: "P122751",
    image: "https://www.sephora.com/productimages/sku/s70680-main-grid.jpg",
    name: "CLINIQUE",
    price: 22.0,
    category: "Lip",
  },
  {
    id: "P409523",
    image: "https://www.sephora.com/productimages/sku/s2481943-main-grid.jpg",
    name: "Urban Decay",
    price: 19.0,
    category: "Lip",
  },
  {
    id: "P236816",
    image: "https://www.sephora.com/productimages/sku/s2579340-main-grid.jpg",
    name: "Dior",
    price: 38.0,
    category: "Lip",
  },
  {
    id: "P458268",
    image: "https://www.sephora.com/productimages/sku/s2447738-main-grid.jpg",
    name: "Charlotte Tilbury",
    price: 25.0,
    category: "Lip",
  },
  {
    id: "P67988453",
    image: "https://www.sephora.com/productimages/sku/s1925965-main-grid.jpg",
    name: "Fenty Beauty by Rihanna",
    price: 20.0,
    category: "Lip",
  },
  {
    id: "P1272",
    image: "https://www.sephora.com/productimages/sku/s2264638-main-grid.jpg",
    name: "Benefit Cosmetics",
    price: 33.0,
    category: "Lip",
  },
  {
    id: "P186805",
    image: "https://www.sephora.com/productimages/sku/s2635654-main-grid.jpg",
    name: "Dior",
    price: 40.0,
    category: "Lip",
  },
  {
    id: "P433516",
    image: "https://www.sephora.com/productimages/sku/s2116515-main-grid.jpg",
    name: "Charlotte Tilbury",
    price: 24.0,
    category: "Lip",
  },
  {
    id: "P405601",
    image:
      "https://www.sephora.com/productimages/sku/s1779271-main-grid.jpg?pb=2020-03-sephora-clean-2019",
    name: "tarte",
    price: 19.0,
    category: "Lip",
  },

  {
    id: "P9798778",
    image:
      "https://www.sephora.com/productimages/sku/s2518959-main-grid.jpg?pb=allure-2022-bestofbeauty-badge",
    name: "Rare Beauty by Selena Gomez",
    price: 20.0,
    category: "Cheek",
  },
  {
    id: "P432668",
    image:
      "https://www.sephora.com/productimages/sku/s2404721-main-grid.jpg?pb=2020-03-sephora-clean-2019",
    name: "Drunk Elephant",
    price: 36.0,
    category: "Cheek",
  },
  {
    id: "P479343",
    image: "https://www.sephora.com/productimages/sku/s2518934-main-grid.jpg",
    name: "Rare Beauty by Selena Gomez",
    price: 23.0,
    category: "Cheek",
  },
  {
    id: "P454762",
    image: "https://www.sephora.com/productimages/sku/s2328375-main-grid.jpg",
    name: "Dior",
    price: 39.0,
    category: "Cheek",
  },
  {
    id: "P18975403",
    image: "https://www.sephora.com/productimages/sku/s2589927-main-grid.jpg",
    name: "Fenty Beauty by Rihanna",
    price: 28.0,
    category: "Cheek",
  },
  {
    id: "P1272",
    image: "https://www.sephora.com/productimages/sku/s2264638-main-grid.jpg",
    name: "Benefit Cosmetics",
    price: 33.0,
    category: "Cheek",
  },
  {
    id: "P501530",
    image: "https://www.sephora.com/productimages/sku/s2618916-main-grid.jpg",
    name: "PATRICK TA",
    price: 58.0,
    category: "Cheek",
  },
  {
    id: "P290636",
    image: "https://www.sephora.com/productimages/sku/s2520419-main-grid.jpg",
    name: "Benefit Cosmetics",
    price: 18.0,
    category: "Cheek",
  },
  {
    id: "P2855",
    image: "https://www.sephora.com/productimages/sku/s2296986-main-grid.jpg",
    name: "NARS",
    price: 16.0,
    category: "Cheek",
  },
  {
    id: "P472327",
    image:
      "https://www.sephora.com/productimages/sku/s2457299-main-grid.jpg?pb=allure-2022-bestofbeauty-badge",
    name: "MAKEUP BY MARIO",
    price: 30.0,
    category: "Cheek",
  },
  {
    id: "P404797",
    image:
      "https://www.sephora.com/productimages/sku/s2487007-main-grid.jpg?pb=2020-03-sephora-clean-2019",
    name: "MILK MAKEUP",
    price: 22.0,
    category: "Cheek",
  },
  {
    id: "P502429",
    image: "https://www.sephora.com/productimages/sku/s2614857-main-grid.jpg",
    name: "tarte",
    price: 39.0,
    category: "Cheek",
  },

  {
    id: "P501536",
    image: "https://www.sephora.com/productimages/sku/s2619898-main-grid.jpg",
    name: "Givenchy",
    price: 50.0,
    category: "Value & Gift Sets",
  },
  {
    id: "P501525",
    image: "https://www.sephora.com/productimages/sku/s2612216-main-grid.jpg",
    name: "Too Faced",
    price: 54.0,
    category: "Value & Gift Sets",
  },
  {
    id: "P501401",
    image: "https://www.sephora.com/productimages/sku/s2614840-main-grid.jpg",
    name: "tarte",
    price: 54.0,
    category: "Value & Gift Sets",
  },
  {
    id: "P502439",
    image: "https://www.sephora.com/productimages/sku/s2614873-main-grid.jpg",
    name: "tarte",
    price: 40.0,
    category: "Value & Gift Sets",
  },
  {
    id: "P5013504",
    image: "https://www.sephora.com/productimages/sku/s2619096-main-grid.jpg",
    name: "PAT McGRATH LABS",
    price: 82.0,
    category: "Value & Gift Sets",
  },
  {
    id: "P5013050",
    image: "https://www.sephora.com/productimages/sku/s2614659-main-grid.jpg",
    name: "Anastasia Beverly Hills",
    price: 39.0,
    category: "Value & Gift Sets",
  },
  {
    id: "P381000",
    image: "https://www.sephora.com/productimages/sku/s1533439-main-grid.jpg",
    name: "Too Faced",
    price: 42.5,
    category: "Value & Gift Sets",
  },
  {
    id: "P501450",
    image: "https://www.sephora.com/productimages/sku/s2614824-main-grid.jpg",
    name: "Benefit Cosmetics",
    price: 42.0,
    category: "Value & Gift Sets",
  },
  {
    id: "P502266",
    image: "https://www.sephora.com/productimages/sku/s2607547-main-grid.jpg",
    name: "CLINIQUE",
    price: 35.0,
    category: "Value & Gift Sets",
  },
  {
    id: "P502510",
    image: "https://www.sephora.com/productimages/sku/s2612208-main-grid.jpg",
    name: "Too Faced",
    price: 42.0,
    category: "Value & Gift Sets",
  },
  {
    id: "P502430",
    image: "https://www.sephora.com/productimages/sku/s2612224-main-grid.jpg",
    name: "Too Faced",
    price: 54.0,
    category: "Value & Gift Sets",
  },

  {
    id: "P501535",
    image: "https://www.sephora.com/productimages/sku/s2612216-main-grid.jpg",
    name: "Too Faced",
    price: 54.0,
    category: "Makeup Palettes",
  },
  {
    id: "P501501",
    image: "https://www.sephora.com/productimages/sku/s2614840-main-grid.jpg",
    name: "tarte",
    price: 54.0,
    category: "Makeup Palettes",
  },
  {
    id: "P5013154",
    image: "https://www.sephora.com/productimages/sku/s2619096-main-grid.jpg",
    name: "PAT McGRATH LABS",
    price: 82.0,
    category: "Makeup Palettes",
  },
  {
    id: "P502530",
    image: "https://www.sephora.com/productimages/sku/s2618916-main-grid.jpg",
    name: "PATRICK TA",
    price: 58.0,
    category: "Makeup Palettes",
  },
  {
    id: "P502500",
    image: "https://www.sephora.com/productimages/sku/s2612208-main-grid.jpg",
    name: "Too Faced",
    price: 42.0,
    category: "Makeup Palettes",
  },
  {
    id: "P432502",
    image: "https://www.sephora.com/productimages/sku/s2087849-main-grid.jpg",
    name: "Dior",
    price: 45.0,
    category: "Makeup Palettes",
  },
  {
    id: "P502470",
    image:
      "https://www.sephora.com/productimages/sku/s2614923-main-grid.jpg?pb=2020-03-sephora-clean-2019",
    name: "tarte",
    price: 49.0,
    category: "Makeup Palettes",
  },
  {
    id: "P501512",
    image: "https://www.sephora.com/productimages/sku/s2603819-main-grid.jpg",
    name: "Danessa Myricks Beauty",
    price: 125.0,
    category: "Makeup Palettes",
  },
  {
    id: "P501527",
    image: "https://www.sephora.com/productimages/sku/s2599660-main-grid.jpg",
    name: "MAKEUP BY MARIO",
    price: 68.0,
    category: "Makeup Palettes",
  },
  {
    id: "P501365",
    image:
      "https://www.sephora.com/productimages/sku/s2579704-main-grid.jpg?pb=2020-03-sephora-value-2020",
    name: "SEPHORA COLLECTION",
    price: 36.0,
    category: "Makeup Palettes",
  },
  {
    id: "P425909",
    image: "https://www.sephora.com/productimages/sku/s2137271-main-grid.jpg",
    name: "HUDA BEAUTY",
    price: 27.0,
    category: "Makeup Palettes",
  },
  {
    id: "P432504",
    image: "https://www.sephora.com/productimages/sku/s2191435-main-grid.jpg",
    name: "Dior",
    price: 49.0,
    category: "Makeup Palettes",
  },
  {
    id: "P501441",
    image: "https://www.sephora.com/productimages/sku/s2618445-main-grid.jpg",
    name: "Melt Cosmetics",
    price: 38.0,
    category: "Makeup Palettes",
  },

  {
    id: "P503698",
    image: "https://www.sephora.com/productimages/sku/s2648020-main-grid.jpg",
    name: "MAKEUP BY MARIO",
    price: 30.0,
    category: "Brushes & Applicators",
  },
  {
    id: "P228913",
    image:
      "https://www.sephora.com/productimages/sku/s2230829-main-grid.jpg?pb=allure-hall-of-fame-best-of-beauty",
    name: "beautyblender",
    price: 20.0,
    category: "Brushes & Applicators",
  },
  {
    id: "P434014",
    image: "https://www.sephora.com/productimages/sku/s2097400-main-grid.jpg",
    name: "beautyblender",
    price: 15.0,
    category: "Brushes & Applicators",
  },
  {
    id: "P502332",
    image: "https://www.sephora.com/productimages/sku/s2614915-main-grid.jpg",
    name: "tarte",
    price: 39.0,
    category: "Brushes & Applicators",
  },
  {
    id: "P479342",
    image: "https://www.sephora.com/productimages/sku/s2518942-main-grid.jpg",
    name: "Rare Beauty by Selena Gomez",
    price: 22.0,
    category: "Brushes & Applicators",
  },
  {
    id: "P469063",
    image:
      "https://www.sephora.com/productimages/sku/s2398022-main-grid.jpg?pb=2020-03-sephora-value-2020",
    name: "SEPHORA COLLECTION",
    price: 69.0,
    category: "Brushes & Applicators",
  },
  {
    id: "P469055",
    image:
      "https://www.sephora.com/productimages/sku/s2398014-main-grid.jpg?pb=2020-03-sephora-value-2020",
    name: "SEPHORA COLLECTION",
    price: 49.0,
    category: "Brushes & Applicators",
  },
  {
    id: "P17484987",
    image: "https://www.sephora.com/productimages/sku/s2362424-main-grid.jpg",
    name: "Rare Beauty by Selena Gomez",
    price: 16.0,
    category: "Brushes & Applicators",
  },
  {
    id: "P420019",
    image:
      "https://www.sephora.com/productimages/sku/s2290039-main-grid.jpg?pb=2020-03-sephora-value-2020",
    name: "SEPHORA COLLECTION",
    price: 20.0,
    category: "Brushes & Applicators",
  },
  {
    id: "P469079",
    image:
      "https://www.sephora.com/productimages/sku/s2398006-main-grid.jpg?pb=2020-03-sephora-value-2020",
    name: "SEPHORA COLLECTION",
    price: 29.0,
    category: "Brushes & Applicators",
  },
  {
    id: "P04141879",
    image: "https://www.sephora.com/productimages/sku/s2362408-main-grid.jpg",
    name: "Rare Beauty by Selena Gomez",
    price: 28.0,
    category: "Brushes & Applicators",
  },
  {
    id: "P39587854",
    image: "https://www.sephora.com/productimages/sku/s2362416-main-grid.jpg",
    name: "Rare Beauty by Selena Gomez",
    price: 14.0,
    category: "Brushes & Applicators",
  },

  {
    id: "P502493",
    image: "https://www.sephora.com/productimages/sku/s2616514-main-grid.jpg",
    name: "The Original MakeUp Eraser",
    price: 25.0,
    category: "Accessories",
  },
  {
    id: "P244437",
    image:
      "https://www.sephora.com/productimages/sku/s1201474-main-grid.jpg?pb=2020-03-allure-best-2018",
    name: "Shiseido",
    price: 6.0,
    category: "Accessories",
  },
  {
    id: "P126301",
    image: "https://www.sephora.com/productimages/sku/s886267-main-grid.jpg",
    name: "CLINIQUE",
    price: 13.0,
    category: "Accessories",
  },
  {
    id: "P459143",
    image:
      "https://www.sephora.com/productimages/sku/s2369916-main-grid.jpg?pb=2020-03-sephora-clean-2019",
    name: "Wishful",
    price: 35.0,
    category: "Accessories",
  },
  {
    id: "P502420",
    image: "https://www.sephora.com/productimages/sku/s2627347-main-grid.jpg",
    name: "Shiseido",
    price: 23.0,
    category: "Accessories",
  },
  {
    id: "P479642",
    image: "https://www.sephora.com/productimages/sku/s2530665-main-grid.jpg",
    name: "The Original MakeUp Eraser",
    price: 25.0,
    category: "Accessories",
  },
  {
    id: "P471219",
    image: "https://www.sephora.com/productimages/sku/s2457190-main-grid.jpg",
    name: "Anastasia Beverly Hills",
    price: 17.0,
    category: "Accessories",
  },
  {
    id: "P467247",
    image:
      "https://www.sephora.com/productimages/sku/s2418853-main-grid.jpg?pb=2020-03-sephora-clean-2019",
    name: "Fenty Skin",
    price: 14.0,
    category: "Accessories",
  },
  {
    id: "P455996",
    image: "https://www.sephora.com/productimages/sku/s2497121-main-grid.jpg",
    name: "SEPHORA COLLECTION",
    price: 8.0,
    category: "Accessories",
  },
  {
    id: "P276319",
    image:
      "https://www.sephora.com/productimages/sku/s1258284-main-grid.jpg?pb=2020-03-sephora-value-2020",
    name: "SEPHORA COLLECTION",
    price: 11.0,
    category: "Accessories",
  },
  {
    id: "P442566",
    image:
      "https://www.sephora.com/productimages/sku/s2170355-main-grid.jpg?pb=2020-03-allure-clean-2019",
    name: "Drunk Elephant",
    price: 34.0,
    category: "Accessories",
  },
  {
    id: "P428809",
    image:
      "https://www.sephora.com/productimages/sku/s2549046-main-grid.jpg?pb=2020-03-sephora-value-2020",
    name: "SEPHORA COLLECTION",
    price: 45.0,
    category: "Accessories",
  },

  {
    id: "P404918",
    image:
      "https://www.sephora.com/productimages/sku/s1991868-main-grid.jpg?pb=2020-03-allure-best-2018",
    name: "Deborah Lippmann",
    price: 14.0,
    category: "Nail",
  },
  {
    id: "P474053",
    image: "https://www.sephora.com/productimages/sku/s2560316-main-grid.jpg",
    name: "Gucci",
    price: 33.0,
    category: "Nail",
  },
  {
    id: "P379408",
    image: "https://www.sephora.com/productimages/sku/s1495811-main-grid.jpg",
    name: "Dior",
    price: 30.0,
    category: "Nail",
  },
  {
    id: "P500858",
    image: "https://www.sephora.com/productimages/sku/s2607950-main-grid.jpg",
    name: "Glamnetic",
    price: 15.0,
    category: "Nail",
  },
  {
    id: "P435832",
    image:
      "https://www.sephora.com/productimages/sku/s2110971-main-grid.jpg?pb=2020-03-sephora-value-2020",
    name: "SEPHORA COLLECTION",
    price: 5.0,
    category: "Nail",
  },
  {
    id: "P416778",
    image:
      "https://www.sephora.com/productimages/sku/s1923358-main-grid.jpg?pb=2020-03-allure-best-2018",
    name: "Deborah Lippmann",
    price: 20.0,
    category: "Nail",
  },
  {
    id: "P396014",
    image: "https://www.sephora.com/productimages/sku/s1702539-main-grid.jpg",
    name: "Deborah Lippmann",
    price: 45.0,
    category: "Nail",
  },
  {
    id: "P501802",
    image: "https://www.sephora.com/productimages/sku/s2608818-main-grid.jpg",
    name: "NAILS INC.",
    price: 8.99,
    category: "Nail",
  },
  {
    id: "P388616",
    image: "https://www.sephora.com/productimages/sku/s1634310-main-grid.jpg",
    name: "NAILS INC.",
    price: 15.0,
    category: "Nail",
  },
  {
    id: "P419467",
    image: "https://www.sephora.com/productimages/sku/s1944297-main-grid.jpg",
    name: "NAILS INC.",
    price: 15.0,
    category: "Nail",
  },
  {
    id: "P387512",
    image:
      "https://www.sephora.com/productimages/sku/s1630292-main-grid.jpg?pb=allure-best-2020",
    name: "L'Occitane",
    price: 20.0,
    category: "Nail",
  },
  {
    id: "P381210",
    image: "https://www.sephora.com/productimages/sku/s1542034-main-grid.jpg",
    name: "Deborah Lippmann",
    price: 20.0,
    category: "Nail",
  },
  {
    id: "P472066",
    image:
      "https://www.sephora.com/productimages/sku/s2414696-main-grid.jpg?pb=2020-03-sephora-value-2020",
    name: "SEPHORA COLLECTION",
    price: 24.0,
    category: "Nail",
  },
  {
    id: "P503163",
    image: "https://www.sephora.com/productimages/sku/s2631588-main-grid.jpg",
    name: "NAILS INC.",
    price: 22.0,
    category: "Nail",
  },
  {
    id: "P503068",
    image: "https://www.sephora.com/productimages/sku/s2633261-main-grid.jpg",
    name: "Glamnetic",
    price: 7.0,
    category: "Nail",
  },
  {
    id: "P460629",
    image: "https://www.sephora.com/productimages/sku/s2376556-main-grid.jpg",
    name: "NAILS INC.",
    price: 37.5,
    category: "Nail",
  },

  {
    id: "P9798978",
    image:
      "https://www.sephora.com/productimages/sku/s2518959-main-grid.jpg?pb=allure-2022-bestofbeauty-badge",
    name: "Rare Beauty by Selena Gomez",
    price: 20.0,
    category: "Vegan",
  },
  {
    id: "P3885577",
    image: "https://www.sephora.com/productimages/sku/s2362168-main-grid.jpg",
    name: "Rare Beauty by Selena Gomez",
    price: 22.0,
    category: "Vegan",
  },
  {
    id: "P456551",
    image:
      "https://www.sephora.com/productimages/sku/s2333771-main-grid.jpg?pb=clean-planet-positive-badge-2021",
    name: "Kosas",
    price: 15.0,
    category: "Vegan",
  },
  {
    id: "P4683471",
    image: "https://www.sephora.com/productimages/sku/s2411486-main-grid.jpg",
    name: "Anastasia Beverly Hills",
    price: 23.0,
    category: "Vegan",
  },
  {
    id: "P5011354",
    image: "https://www.sephora.com/productimages/sku/s2619096-main-grid.jpg",
    name: "PAT McGRATH LABS",
    price: 22.0,
    category: "Vegan",
  },
  {
    id: "P441813",
    image:
      "https://www.sephora.com/productimages/sku/s2169423-main-grid.jpg?pb=2020-03-sephora-clean-2019",
    name: "MILK MAKEUP",
    price: 18.0,
    category: "Vegan",
  },
  {
    id: "P202633",
    image: "https://www.sephora.com/productimages/sku/s2372530-main-grid.jpg",
    name: "Anastasia Beverly Hills",
    price: 25.0,
    category: "Vegan",
  },
  {
    id: "P448869",
    image: "https://www.sephora.com/productimages/sku/s2244804-main-grid.jpg",
    name: "Charlotte Tilbury",
    price: 46.0,
    category: "Vegan",
  },
  {
    id: "P502185",
    image:
      "https://www.sephora.com/productimages/sku/s2597268-main-grid.jpg?pb=2020-03-sephora-clean-2019",
    name: "HAUS LABS BY LADY GAGA",
    price: 45.0,
    category: "Vegan",
  },
  {
    id: "P404787",
    image:
      "https://www.sephora.com/productimages/sku/s2487007-main-grid.jpg?pb=2020-03-sephora-clean-2019",
    name: "MILK MAKEUP",
    price: 22.0,
    category: "Vegan",
  },
  {
    id: "P455418",
    image:
      "https://www.sephora.com/productimages/sku/s2333607-main-grid.jpg?pb=2020-03-sephora-clean-2019",
    name: "ILIA",
    price: 48.0,
    category: "Vegan",
  },

  {
    id: "P501545",
    image: "https://www.sephora.com/productimages/sku/s2612216-main-grid.jpg",
    name: "Too Faced",
    price: 54.0,
    category: "Mini Size",
  },
  {
    id: "P467607",
    image: "https://www.sephora.com/productimages/sku/s2407278-main-grid.jpg",
    name: "Charlotte Tilbury",
    price: 17.0,
    category: "Mini Size",
  },
  {
    id: "P458278",
    image: "https://www.sephora.com/productimages/sku/s2447738-main-grid.jpg",
    name: "Charlotte Tilbury",
    price: 25.0,
    category: "Mini Size",
  },
  {
    id: "P461148",
    image: "https://www.sephora.com/productimages/sku/s2368447-main-grid.jpg",
    name: "Charlotte Tilbury",
    price: 21.0,
    category: "Mini Size",
  },
  {
    id: "P467754",
    image: "https://www.sephora.com/productimages/sku/s2407344-main-grid.jpg",
    name: "Charlotte Tilbury",
    price: 26.0,
    category: "Mini Size",
  },
  {
    id: "P422077",
    image: "https://www.sephora.com/productimages/sku/s2245363-main-grid.jpg",
    name: "NARS",
    price: 14.0,
    category: "Mini Size",
  },
  {
    id: "P441814",
    image:
      "https://www.sephora.com/productimages/sku/s2191252-main-grid.jpg?pb=2020-03-sephora-clean-2019",
    name: "MILK MAKEUP",
    price: 18.0,
    category: "Mini Size",
  },
  {
    id: "P422083",
    image: "https://www.sephora.com/productimages/sku/s2250520-main-grid.jpg",
    name: "Laura Mercier",
    price: 24.0,
    category: "Mini Size",
  },
  {
    id: "P444603",
    image: "https://www.sephora.com/productimages/sku/s2227312-main-grid.jpg",
    name: "Grande Cosmetics",
    price: 36.0,
    category: "Mini Size",
  },
  {
    id: "P425919",
    image: "https://www.sephora.com/productimages/sku/s2137271-main-grid.jpg",
    name: "HUDA BEAUTY",
    price: 27.0,
    category: "Mini Size",
  },
  {
    id: "P454751",
    image: "https://www.sephora.com/productimages/sku/s2311330-main-grid.jpg",
    name: "Anastasia Beverly Hills",
    price: 9.0,
    category: "Mini Size",
  },
  {
    id: "P502503",
    image: "https://www.sephora.com/productimages/sku/s2612190-main-grid.jpg",
    name: "Too Faced",
    price: 29.0,
    category: "Mini Size",
  },
  {
    id: "P468653",
    image:
      "https://www.sephora.com/productimages/sku/s2441129-main-grid.jpg?pb=2020-03-sephora-clean-2019",
    name: "Freck Beauty",
    price: 28.0,
    category: "Mini Size",
  },
  {
    id: "P425938",
    image:
      "https://www.sephora.com/productimages/sku/s2492510-main-grid.jpg?pb=2020-03-allure-best-2018",
    name: "Armani Beauty",
    price: 45.0,
    category: "Mini Size",
  },
];
export default data;
